all_fed_agencies_array = [
"Administrative Conference of the United States",
"Administrative Office of United States Courts",
"Advisory Council on Historic Preservation",
"African Development Foundation",
"Agency for International Development",
"International Development Cooperation Agency",
"Agriculture Department",
"Advocacy and Outreach Office",
"Agricultural Marketing Service",
"Agricultural Research Service",
"Animal and Plant Health Inspection Service",
"Commodity Credit Corporation",
"Cooperative State Research, Education, and Extension Service",
"Economic Analysis Staff",
"Economic Research Service",
"Energy Policy and New Uses Office",
"Farm Service Agency",
"Federal Crop Insurance Corporation",
"Food and Consumer Service",
"Food and Nutrition Service",
"Food Safety and Inspection Service",
"Foreign Agricultural Service",
"Forest Service",
"Inspector General Office, Agriculture Department",
"National Agricultural Library",
"National Agricultural Statistics Service",
"National Institute of Food and Agriculture",
"Natural Resources Conservation Service",
"Office of the Chief Financial Officer, Agriculture Department",
"Operations Office",
"Procurement and Property Management, Office of",
"Risk Management Agency",
"Rural Business-Cooperative Service",
"Rural Housing and Community Development Service",
"Rural Housing Service",
"Rural Telephone Bank",
"Rural Utilities Service",
"Transportation Office",
"U.S. Codex Office",
"Air Quality National Commission",
"Air Transportation Stabilization Board",
"American Battle Monuments Commission",
"Amtrak Reform Council",
"Antitrust Modernization Commission",
"Appalachian Regional Commission",
"Appalachian States Low-Level Radioactive Waste Commission",
"Architect of the Capitol",
"Architectural and Transportation Barriers Compliance Board",
"Arctic Research Commission",
"Armed Forces Retirement Home",
"Arms Control and Disarmament Agency",
"Assassination Records Review Board",
"Barry M. Goldwater Scholarship and Excellence in Education Foundation",
"Bipartisan Commission on Entitlement and Tax Reform",
"Board of Directors of the Hope for Homeowners Program",
"Broadcasting Board of Governors",
"Census Monitoring Board",
"Central Intelligence Agency",
"Chemical Safety and Hazard Investigation Board",
"Christopher Columbus Quincentenary Jubilee Commission",
"Civil Rights Commission",
"Commerce Department",
"Census Bureau",
"Economic Analysis Bureau",
"Economic Development Administration",
"Economics and Statistics Administration",
"Export Administration Bureau",
"Foreign-Trade Zones Board",
"Industry and Security Bureau",
"International Trade Administration",
"Minority Business Development Agency",
"National Institute of Standards and Technology",
"National Oceanic and Atmospheric Administration",
"National Shipping Authority",
"National Technical Information Service",
"National Telecommunications and Information Administration",
"Patent and Trademark Office",
"Technology Administration",
"Travel and Tourism Administration",
"Commission of Fine Arts",
"Commission on Immigration Reform",
"Commission on Protecting and Reducing Government Secrecy",
"Commission on Review of Overseas Military Facility Structure of the United States",
"Commission on Structural Alternatives for the Federal Courts of Appeals",
"Commission on the Advancement of Federal Law Enforcement",
"Commission on the Bicentennial of the United States Constitution",
"Commission on the Future of the United States Aerospace Industry",
"Commission on the Social Security Notch Issue",
"Committee for Purchase From People Who Are Blind or Severely Disabled",
"Committee for the Implementation of Textile Agreements",
"Commodity Futures Trading Commission",
"Competitiveness Policy Council",
"Congressional Budget Office",
"Consumer Financial Protection Bureau",
"Consumer Product Safety Commission",
"Coordinating Council on Juvenile Justice and Delinquency Prevention",
"Corporation for National and Community Service",
"Council of the Inspectors General on Integrity and Efficiency",
"Court Services and Offender Supervision Agency for the District of Columbia",
"Crime and Security in U.S. Seaports, Interagency Commission",
"Defense Base Closure and Realignment Commission",
"Defense Department",
"Air Force Department",
"Army Department",
"Defense Acquisition Regulations System",
"Defense Contract Audit Agency",
"Defense Criminal Investigative Service",
"Defense Information Systems Agency",
"Defense Intelligence Agency",
"Defense Investigative Service",
"Defense Logistics Agency",
"Defense Mapping Agency",
"Defense Special Weapons Agency",
"Engineers Corps",
"National Geospatial-Intelligence Agency",
"National Security Agency/Central Security Service",
"Navy Department",
"Uniformed Services University of the Health Sciences",
"Defense Nuclear Facilities Safety Board",
"Delaware River Basin Commission",
"Denali Commission",
"Education Department",
"Election Assistance Commission",
"Electronic Commerce Advisory Commission",
"Emergency Oil and Gas Guaranteed Loan Board",
"Emergency Steel Guarantee Loan Board",
"Energy Department",
"Alaska Power Administration",
"Bonneville Power Administration",
"Energy Efficiency and Renewable Energy Office",
"Energy Information Administration",
"Energy Research Office",
"Environment Office, Energy Department",
"Federal Energy Regulatory Commission",
"Hearings and Appeals Office, Energy Department",
"Minority Economic Impact Office",
"National Nuclear Security Administration",
"Nuclear Energy Office",
"Southeastern Power Administration",
"Southwestern Power Administration",
"Western Area Power Administration",
"Environmental Protection Agency",
"Equal Employment Opportunity Commission",
"Executive Council on Integrity and Efficiency",
"Executive Office of the President",
"Administration Office, Executive Office of the President",
"Council on Environmental Quality",
"Counsel to the President",
"Export-Import Bank",
"Farm Credit Administration",
"Farm Credit System Insurance Corporation",
"Federal Accounting Standards Advisory Board",
"Federal Acquisition Regulation System",
"Federal Communications Commission",
"Federal Deposit Insurance Corporation",
"Federal Election Commission",
"Federal Financial Institutions Examination Council",
"Federal Housing Finance Agency",
"Federal Housing Finance Board",
"Federal Labor Relations Authority",
"Federal Service Impasses Panel",
"Federal Maritime Commission",
"Federal Mediation and Conciliation Service",
"Federal Mine Safety and Health Review Commission",
"Federal Pay, Advisory Committee",
"Federal Permitting Improvement Steering Council",
"Federal Register, Administrative Committee",
"Federal Reserve System",
"Federal Retirement Thrift Investment Board",
"Federal Trade Commission",
"Financial Crisis Inquiry Commission",
"Financial Stability Oversight Council",
"Foreign Service Grievance Board",
"Foreign Service Impasse Disputes Panel",
"Foreign Service Labor Relations Board",
"General Services Administration",
"Geographic Names Board",
"Government Accountability Office",
"Government Ethics Office",
"Government Publishing Office",
"Gulf Coast Ecosystem Restoration Council",
"Harry S. Truman Scholarship Foundation",
"Health and Human Services Department",
"Agency for Healthcare Research and Quality",
"Agency for Toxic Substances and Disease Registry",
"Aging Administration",
"Centers for Disease Control and Prevention",
"Centers for Medicare & Medicaid Services",
"Child Support Enforcement Office",
"Children and Families Administration",
"Community Living Administration",
"Family Assistance Office",
"Food and Drug Administration",
"Health Care Finance Administration",
"Health Resources and Services Administration",
"Indian Health Service",
"Inspector General Office, Health and Human Services Department",
"National Institutes of Health",
"National Library of Medicine",
"Program Support Center",
"Public Health Service",
"Refugee Resettlement Office",
"Substance Abuse and Mental Health Services Administration",
"Homeland Security Department",
"Coast Guard",
"Federal Emergency Management Agency",
"Federal Law Enforcement Training Center",
"National Communications System",
"Secret Service",
"Transportation Security Administration",
"U.S. Citizenship and Immigration Services",
"U.S. Customs and Border Protection",
"U.S. Immigration and Customs Enforcement",
"Housing and Urban Development Department",
"Federal Housing Enterprise Oversight Office",
"Government National Mortgage Association",
"Indian Arts and Crafts Board",
"Institute of American Indian and Alaska Native Culture and Arts Development",
"Inter-American Foundation",
"Interagency Floodplain Management Review Committee",
"Intergovernmental Relations Advisory Commission",
"Interior Department",
"Fish and Wildlife Service",
"Geological Survey",
"Hearings and Appeals Office, Interior Department",
"Indian Affairs Bureau",
"Indian Trust Transition Office",
"Land Management Bureau",
"Minerals Management Service",
"Mines Bureau",
"National Biological Service",
"National Civilian Community Corps",
"National Indian Gaming Commission",
"National Park Service",
"Natural Resources Revenue Office",
"Ocean Energy Management Bureau",
"Ocean Energy Management, Regulation, and Enforcement Bureau",
"Reclamation Bureau",
"Safety and Environmental Enforcement Bureau",
"Special Trustee for American Indians Office",
"Surface Mining Reclamation and Enforcement Office",
"International Boundary and Water Commission, United States and Mexico",
"International Broadcasting Board",
"International Joint Commission-United States and Canada",
"International Organizations Employees Loyalty Board",
"International Trade Commission",
"Interstate Commerce Commission",
"James Madison Memorial Fellowship Foundation",
"Japan-United States Friendship Commission",
"Joint Board for Enrollment of Actuaries",
"    Judicial Conference of the United States",
"Judicial Review Commission on Foreign Asset Control",
"Justice Department",
"Alcohol, Tobacco, Firearms, and Explosives Bureau",
"Antitrust Division",
"Drug Enforcement Administration",
"Executive Office for Immigration Review",
"Federal Bureau of Investigation",
"Federal Prison Industries",
"Foreign Claims Settlement Commission",
"Immigration and Naturalization Service",
"Justice Programs Office",
"Juvenile Justice and Delinquency Prevention Office",
"National Institute of Corrections",
"National Institute of Justice",
"Parole Commission",
"Prisons Bureau",
"United States Marshals Service",
"Labor Department",
"Benefits Review Board",
"Disability Employment Policy Office",
"Employee Benefits Security Administration",
"Employees Compensation Appeals Board",
"Employment and Training Administration",
"Employment Standards Administration",
"Federal Contract Compliance Programs Office",
"Labor Statistics Bureau",
"Labor-Management Standards Office",
"Mine Safety and Health Administration",
"Occupational Safety and Health Administration",
"Pension and Welfare Benefits Administration",
"Veterans Employment and Training Service",
"Wage and Hour Division",
"Workers Compensation Programs Office",
"Legal Services Corporation",
"Library of Congress",
"Copyright Office, Library of Congress",
"Copyright Royalty Board",
"Copyright Royalty Judges",
"Local Television Loan Guarantee Board",
"Management and Budget Office",
"Federal Procurement Policy Office",
"Marine Mammal Commission",
"Medicare Payment Advisory Commission",
"Merit Systems Protection Board",
"Military Compensation and Retirement Modernization Commission",
"Millennium Challenge Corporation",
"Mississippi River Commission",
"Morris K. Udall and Stewart L. Udall Foundation",
"National Aeronautics and Space Administration",
"National Archives and Records Administration",
"Federal Register Office",
"Information Security Oversight Office",
"National Historical Publications and Records Commission",
"Office of Government Information Services",
"National Bankruptcy Review Commission",
"National Bipartisan Commission on Future of Medicare",
"National Capital Planning Commission",
"National Commission on Intermodal Transportation",
"National Commission on Libraries and Information Science",
"National Commission on Manufactured Housing",
"National Commission on Military, National, and Public Service",
"National Commission on Terrorist Attacks Upon the United States",
"National Commission on the Cost of Higher Education",
"National Consumer Cooperative Bank",
"National Council on Disability",
"National Counterintelligence Center",
"National Credit Union Administration",
"National Crime Prevention and Privacy Compact Council",
"National Economic Council",
"National Education Goals Panel",
"National Foundation on the Arts and the Humanities",
"Federal Council on the Arts and the Humanities",
"Institute of Museum and Library Services",
"National Endowment for the Arts",
"National Endowment for the Humanities",
"National Gambling Impact Study Commission",
"National Institute for Literacy",
"National Intelligence, Office of the National Director",
"National Labor Relations Board",
"National Mediation Board",
"National Nanotechnology Coordination Office",
"National Partnership for Reinventing Government",
"National Prison Rape Elimination Commission",
"National Railroad Passenger Corporation",
"National Science Foundation",
"National Security Council",
"National Skill Standards Board",
"National Transportation Safety Board",
"National Women's Business Council",
"Navajo and Hopi Indian Relocation Office",
"Neighborhood Reinvestment Corporation",
"Northeast Dairy Compact Commission",
"Northeast Interstate Low-Level Radioactive Waste Commission",
"Nuclear Regulatory Commission",
"Nuclear Waste Technical Review Board",
"Occupational Safety and Health Review Commission",
"Ocean Policy Commission",
"Office of National Drug Control Policy",
"Office of Policy Development",
"Oklahoma City National Memorial Trust",
"Ounce of Prevention Council",
"Overseas Private Investment Corporation",
"Pacific Northwest Electric Power and Conservation Planning Council",
"Panama Canal Commission",
"Peace Corps",
"Pension Benefit Guaranty Corporation",
"Personnel Management Office",
"Physician Payment Review Commission",
"Postal Rate Commission",
"Postal Regulatory Commission",
"Postal Service",
"President's Council on Integrity and Efficiency",
"President's Council on Sustainable Development",
"President's Critical Infrastructure Protection Board",
"President's Economic Policy Advisory Board",
"Presidential Advisory Committee on Gulf War Veterans' Illnesses",
"Presidential Commission on Assignment of Women in the Armed Forces",
"Presidential Documents",
"Presidio Trust",
"Privacy and Civil Liberties Oversight Board",
"Prospective Payment Assessment Commission",
"Railroad Retirement Board",
"Reagan-Udall Foundation for the Food and Drug Administration",
"Recovery Accountability and Transparency Board",
"Regulatory Information Service Center",
"Resolution Trust Corporation",
"Science and Technology Policy Office",
"Securities and Exchange Commission",
"Selective Service System",
"Small Business Administration",
"Smithsonian Institution",
"Social Security Administration",
"Special Counsel Office",
"Special Inspector General for Afghanistan Reconstruction",
"Special Inspector General For Iraq Reconstruction",
"State Department",
"State Justice Institute",
"Surface Transportation Board",
"Susquehanna River Basin Commission",
"Tennessee Valley Authority",
"The White House Office",
"Thrift Depositor Protection Oversight Board",
"Trade and Development Agency",
"Trade Representative, Office of United States",
"Transportation Department",
"Commercial Space Transportation Office",
"Federal Aviation Administration",
"Federal Highway Administration",
"Federal Motor Carrier Safety Administration",
"Federal Railroad Administration",
"Federal Transit Administration",
"Maritime Administration",
"National Highway Traffic Safety Administration",
"Office of Motor Carrier Safety",
"Pipeline and Hazardous Materials Safety Administration",
"Research and Innovative Technology Administration",
"Research and Special Programs Administration",
"Saint Lawrence Seaway Development Corporation",
"Transportation Statistics Bureau",
"Treasury Department",
"Alcohol and Tobacco Tax and Trade Bureau",
"Bureau of the Fiscal Service",
"Community Development Financial Institutions Fund",
"Comptroller of the Currency",
"Customs Service",
"Engraving and Printing Bureau",
"Financial Crimes Enforcement Network",
"Financial Research Office",
"Fiscal Service",
"Foreign Assets Control Office",
"Internal Revenue Service",
"International Investment Office",
"Monetary Offices",
"Public Debt Bureau",
"Thrift Supervision Office",
"United States Mint",
"Twenty-First Century Workforce Commission",
"U.S. House of Representatives",
"U.S. Trade Deficit Review Commission",
"U.S.-China Economic and Security Review Commission",
"United States Enrichment Corporation",
"United States Information Agency",
"United States Institute of Peace",
"United States Sentencing Commission",
"Utah Reclamation Mitigation and Conservation Commission",
"Valles Caldera Trust",
"Veterans Affairs Department",
"Women's Business Enterprise Interagency Committee",
"Women's Progress Commemoration Commission"];